/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vetores;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author a24480
 */
public class Vetore extends javax.swing.JFrame {

    /**
     * Creates new form Vetore
     */
    int vetor[]=new int [9];
    DefaultListModel list = new DefaultListModel();
    int selecionado=0;
    
    
    public Vetore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butN1 = new javax.swing.JButton();
        butN2 = new javax.swing.JButton();
        butN3 = new javax.swing.JButton();
        lblN1 = new javax.swing.JLabel();
        spiN1 = new javax.swing.JSpinner();
        plaN1 = new javax.swing.JScrollPane();
        listN1 = new javax.swing.JList<>();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butN1.setText("Adicionar");
        butN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butN1ActionPerformed(evt);
            }
        });

        butN2.setText("Ordenar");
        butN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butN2ActionPerformed(evt);
            }
        });

        butN3.setText("Remover");
        butN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butN3ActionPerformed(evt);
            }
        });

        lblN1.setText("Vetor");

        listN1.setModel(lista);
        listN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listN1MouseClicked(evt);
            }
        });
        plaN1.setViewportView(listN1);

        lblN3.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butN2)
                            .addComponent(butN1)
                            .addComponent(butN3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(spiN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(plaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lblN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblN2)
                .addGap(38, 38, 38)
                .addComponent(lblN3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(spiN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblN1)
                            .addComponent(lblN2)
                            .addComponent(lblN3))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butN1)
                        .addGap(26, 26, 26)
                        .addComponent(butN2)
                        .addGap(18, 18, 18)
                        .addComponent(butN3))
                    .addComponent(plaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butN1ActionPerformed
        // TODO add your handling code here:
        vetor [selecionado]=Integer.parseInt(spiN1.getValue().toString());
        list.removeAllElements();
        for(int c=0; c< vetor.length; c++){
            list.addElement(vetor[c]);
        }
    }//GEN-LAST:event_butN1ActionPerformed

    private void listN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listN1MouseClicked
        // TODO add your handling code here:
        selecionado=listN1.getSelectedIndex();
        lblN2.setText("(" + selecionado + ")");
        
    }//GEN-LAST:event_listN1MouseClicked

    private void butN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butN2ActionPerformed
        // TODO add your handling code here:
        Arrays.sort(vetor);
        list.removeAllElements();
        for(int c=0; c< vetor.length; c++){
            list.addElement(vetor[c]);
        }
        
    }//GEN-LAST:event_butN2ActionPerformed

    private void butN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butN3ActionPerformed
        // TODO add your handling code here:
        vetor [selecionado]=0;
        list.removeAllElements();
        for(int c=0; c< vetor.length; c++){
            list.addElement(vetor[c]);
    }//GEN-LAST:event_butN3ActionPerformed

        
    }
    public static void main(String args[]) {        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vetore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vetore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vetore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vetore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vetore().setVisible(true);
            }
        });
    }
        
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butN1;
    private javax.swing.JButton butN2;
    private javax.swing.JButton butN3;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JList<String> listN1;
    private javax.swing.JScrollPane plaN1;
    private javax.swing.JSpinner spiN1;
    // End of variables declaration//GEN-END:variables
}