/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Imagem;

import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.PrintStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author a24480
 */
public class Image extends javax.swing.JFrame {

    /**
     * Creates new form Image
     */
    public Image() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butN1 = new javax.swing.JButton();
        txtN1 = new javax.swing.JTextField();
        lblN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butN1.setText("Stop!!");
        butN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butN1ActionPerformed(evt);
            }
        });
        getContentPane().add(butN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 11, -1, -1));

        txtN1.setFont(new java.awt.Font("Impact", 1, 11)); // NOI18N
        txtN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 127, 118, 37));

        lblN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Imagem/Imagens/street.jpg"))); // NOI18N
        getContentPane().add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Graphics g = this.getGraphics();
        g.setColor(Color.gray);
        g.fillRoundRect(210, 165, 30, 300, 10, 10);
        g.setColor(Color.black);
        g.fillOval(95,45,260,265);
        g.setColor(Color.white);
        g.fillOval(100,50,250,250);
        g.setColor(Color.red);
        g.fillOval(120, 75, 210, 210);
        g.setColor(Color.white);
        g.fillRoundRect(175, 165, 100, 30, 10, 10);
    }//GEN-LAST:event_formComponentShown

    private void butN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butN1ActionPerformed
        // TODO add your handling code here:
        txtN1.setText("         Stop!!!!");
    }//GEN-LAST:event_butN1ActionPerformed

    private void txtN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        InputStream music;
        try{
            music= new FileInputStream(new File("src\\audio\\audiostopwav.wav"));
            AudioStream audios=new AudioStream(music);
            AudioPlayer.player.start(audios);
        }
    catch(Exception e){
            Object debugFileWriter = null;
    if (debugFileWriter!=null) e.printStackTrace((PrintStream) debugFileWriter);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Image().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butN1;
    private javax.swing.JLabel lblN1;
    private javax.swing.JTextField txtN1;
    // End of variables declaration//GEN-END:variables
}
